version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./config:/config
      - ../share:/share
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host