version: "3"
services:
  node-red:
    container_name: node-red
    user: "0:0"
    build:
      context: .
      args:
        packages: "ffmpeg"
    env_file:
      - ../secrets/node-red.env
    environment:
      TZ: Asia/Shanghai
    ports:
      - "1880:1880"
    networks:
      - SmartHomeOS
    volumes:
      - ./node-red-data:/data
      - ../share:/share
networks:
  SmartHomeOS:
    external: true